name: Deploy site

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: generate social previews
        run: uv run generate_og_images.py
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
